Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 8086, host: 8086
  config.vm.network "forwarded_port", guest: 8083, host: 8083

  config.vm.provision "file", source: "./provision/dropalldb.sh", destination: "~/dropalldb.sh"
  config.vm.provision "shell", path: "provision/setup.sh"
end
