Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 8086, host: 8086
  config.vm.network "forwarded_port", guest: 8083, host: 8083

  config.vm.provision "shell", inline: <<-SHELL
    wget -q0 https://s3.amazonaws.com/influxdb/influxdb_0.9.1_amd64.deb
    sudo dpkg -i influxdb_0.9.1_amd64.deb
    sudo /etc/init.d/influxdb start
  SHELL
end
